# .streamlit/secrets.toml

[DEEPSEEK]
API_KEY = "sk-e31737152ebc4f4b8a14d886b2a0d398"  # Clé API DeepSeek

[OWM]  # OpenWeatherMap (si utilisé)
API_KEY = "4567def..."

# Autres secrets (ex: base de données)
[DB]
USER = "admin"
PASSWORD = "secure_password123"
