# .streamlit/secrets.toml

[DEEPSEEK]
API_KEY = "ds-sk-1234abc..."  # Clé API DeepSeek

[OWM]  # OpenWeatherMap (si utilisé)
API_KEY = "4567def..."

# Autres secrets (ex: base de données)
[DB]
USER = "admin"
PASSWORD = "secure_password123"
